### ISSUE TITLE
Can't run example due to: DevTools failed to load source map

### ISSUE THREAD

**Issue by gentrexha** [zeriontech/zerion-analytics#1]
Hey everyone,

I've tried running your provided test.html website and ran into this error:

```
DevTools failed to load source map: Could not load content for https://s3.amazonaws.com/web3.analytics/zerion-analytics.umd.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Evgeny has shared an API key with me which I've put into `.env`. Is there anything else I need to do?

**Comment by zerts** [comment]
Hi @gentrexha !

Thank you for your report!

Right now example is broken because of some bugs with packaging tool. 

However, you can use test.html after replacing `"{{ ZERION_API_KEY_V4 || '' }}"` with your actual key. After this you won't need to build anything, just open html file in browser.

**Comment by gentrexha** [comment]
> Hi @gentrexha !
> 
> Thank you for your report!
> 
> Right now example is broken because of some bugs with packaging tool.
> 
> However, you can use test.html after replacing `"{{ ZERION_API_KEY_V4 || '' }}"` with your actual key. After this you won't need to build anything, just open html file in browser.

Hi @zerts , thank you for your response.

Unfortunately, even after putting the key directly into the `.html` file I still receive the same error:

```
DevTools failed to load source map: Could not load content for https://s3.amazonaws.com/web3.analytics/zerion-analytics.umd.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by zerts** [comment]
Looks, like this is not a blocking error. I will try to remove it from the console in the future. But the script should work fine even with it.

**Comment by gentrexha** [comment]
> Looks, like this is not a blocking error. I will try to remove it from the console in the future. But the script should work fine even with it.

Yeah it worked fine. I just had to do everything in the console. Thank you for your help.
